### ISSUE TITLE
Symbol Desktop Wallet 1.0.5 Cannot send using ledger

### ISSUE THREAD

**Issue by Dtbychris** [symbol/xymbassadors#38] opened 2021-07-25 16:57 UTC
( MAC OS ) ** Symbol Desktop Wallet 1.0.5 Cannot send using ledger Change back to 1.0.4 normal sending **

Very important, need to be revised in time

<img width="357" alt="截圖 2021-07-26 上午12 26 46" src="https://user-images.githubusercontent.com/87372647/126906848-081a6d9e-f3be-4da8-8792-9800ee0bb809.png">

**Comment by leoinker** [comment] 2021-07-25 18:17
@Dtbychris Thanks for reporting. 
This bug was already reported here: https://github.com/symbol/symbol-desktop-wallet/issues/1620

The xymbassadors repository is for xymbassador / community management related "issues" (tasks)

**Comment by leoinker** [comment] 2021-07-25 18:18
Duplicate of: https://github.com/symbol/symbol-desktop-wallet/issues/1620

**Closed** 2021-07-25 18:17 UTC
